version: '3.9'

services:
  api-test:
    build: .
    container_name: nest-api-test
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      - MONGO_URL=mongodb://mongo-test:27017
      - MONGO_DATABASE_NAME=fundraisingDB-test
      - NODE_ENV=test
    env_file:
      - .env.test
    depends_on:
      - mongo-test

  mongo-test:
    image: mongo:6
    container_name: mongodb-test
    restart: unless-stopped
    ports:
      - "27019:27017"
    environment:
      - MONGO_URI=${MONGO_URL}/${MONGO_DATABASE_NAME}
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: rootpassword
      #MONGO_INITDB_DATABASE: fundraisingDB
    volumes:
      - mongo_test_data:/data/db

volumes:
  mongo_test_data:
